
    dialect "java"
    
import org.optaplanner.core.api.score.buildin.simple.SimpleScoreHolder;

import com.mplescano.app.poc.optaplanner.knapsack.simple.domain.Bin;
import com.mplescano.app.poc.optaplanner.knapsack.simple.domain.Item;
import com.mplescano.app.poc.optaplanner.knapsack.simple.domain.PackingSolution;

import org.optaplanner.core.api.score.buildin.simple.SimpleScore;

global SimpleScoreHolder scoreHolder;

rule "simpleScore"
	when
		$bin : Bin($free: volume, this != PackingSolution.NULL_BIN )
		accumulate(
		  Item(bin == $bin, $size : size );
		  $sumMass : sum($size);
		  $sumMass > $free
		)
	then
		scoreHolder.addConstraintMatch(kcontext, $free - $sumMass);
end